### ISSUE TITLE
Gracefully handle file naming

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/osmosis-ipfs-driver#3]
For direct, native IPFS file urls the file naming upon consuming should be handled more gracefully when the folder wrapping trick upon adding to IPFS is not used by end users.

E.g. using this url to register an asset:
- `ipfs://QmRhxsFAxPWWHkDcEMXZ1wAuqhCDsswNXzEaDU67wTjLA1`

Will result in a `octet-stream` file blob being downloaded to user's devices as `QmRhxsFAxPWWHkDcEMXZ1wAuqhCDsswNXzEaDU67wTjLA1`, so the OS does not know what to do with it unless user manually renames that file and adds a file ending.

### Proposed solution

Since the MIME type is in the DDO as `file.contentType` we should use that, and when detecting there's no file ending, we should add it based on `file.contentType`. 

So with example above user would end up with a file:
- `QmRhxsFAxPWWHkDcEMXZ1wAuqhCDsswNXzEaDU67wTjLA1.mp4`

But in newer DDO versions we also support `file.name` so when this is set it should take precedence over the above solution.

**Comment by ssallam** [comment]
Brizo is updated to implement the proposed solution: https://github.com/oceanprotocol/brizo/pull/159
